# coding: utf-8

"""
    SPAN Tenure

    This is a simple API which is used to as a demo for using OpenAPI to define specifications.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jayan.smart@spandigital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="SPAN Tenure",
    author_email="jayan.smart@spandigital.com",
    url="",
    keywords=["Swagger", "SPAN Tenure"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is a simple API which is used to as a demo for using OpenAPI to define specifications.  # noqa: E501
    """
)
