# coding: utf-8

"""
    SPAN Tenure

    This is a simple API which is used to as a demo for using OpenAPI to define specifications.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jayan.smart@spandigital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.server_error import ServerError  # noqa: E501
from swagger_client.rest import ApiException


class TestServerError(unittest.TestCase):
    """ServerError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerError(self):
        """Test ServerError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.server_error.ServerError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
