# coding: utf-8

"""
    SPAN Tenure

    This is a simple API which is used to as a demo for using OpenAPI to define specifications.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jayan.smart@spandigital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tenure_by_id(self):
        """Test case for get_tenure_by_id

        get tenure by ID  # noqa: E501
        """
        pass

    def test_patch_tenure(self):
        """Test case for patch_tenure

        Update the start date of an employee.  # noqa: E501
        """
        pass

    def test_post_tenure(self):
        """Test case for post_tenure

        POST new employee information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
