# coding: utf-8

# flake8: noqa
"""
    SPAN Tenure

    This is a simple API which is used to as a demo for using OpenAPI to define specifications.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jayan.smart@spandigital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.employee_info_schema import EmployeeInfoSchema
from swagger_client.models.input_error import InputError
from swagger_client.models.server_error import ServerError
