# coding: utf-8

"""
    SPAN Tenure

    This is a simple API which is used to as a demo for using OpenAPI to define specifications.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jayan.smart@spandigital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EmployeeInfoSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'tenure': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'tenure': 'tenure'
    }

    def __init__(self, id=None, name='Not Available', tenure=None):  # noqa: E501
        """EmployeeInfoSchema - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._tenure = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if tenure is not None:
            self.tenure = tenure

    @property
    def id(self):
        """Gets the id of this EmployeeInfoSchema.  # noqa: E501

        The id of the employee  # noqa: E501

        :return: The id of this EmployeeInfoSchema.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EmployeeInfoSchema.

        The id of the employee  # noqa: E501

        :param id: The id of this EmployeeInfoSchema.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this EmployeeInfoSchema.  # noqa: E501

        The employee name  # noqa: E501

        :return: The name of this EmployeeInfoSchema.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EmployeeInfoSchema.

        The employee name  # noqa: E501

        :param name: The name of this EmployeeInfoSchema.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def tenure(self):
        """Gets the tenure of this EmployeeInfoSchema.  # noqa: E501

        The tenure of an employee in days  # noqa: E501

        :return: The tenure of this EmployeeInfoSchema.  # noqa: E501
        :rtype: int
        """
        return self._tenure

    @tenure.setter
    def tenure(self, tenure):
        """Sets the tenure of this EmployeeInfoSchema.

        The tenure of an employee in days  # noqa: E501

        :param tenure: The tenure of this EmployeeInfoSchema.  # noqa: E501
        :type: int
        """

        self._tenure = tenure

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmployeeInfoSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmployeeInfoSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
