# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmployeeInfoSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str='Not Available', tenure: int=None):  # noqa: E501
        """EmployeeInfoSchema - a model defined in Swagger

        :param id: The id of this EmployeeInfoSchema.  # noqa: E501
        :type id: int
        :param name: The name of this EmployeeInfoSchema.  # noqa: E501
        :type name: str
        :param tenure: The tenure of this EmployeeInfoSchema.  # noqa: E501
        :type tenure: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'tenure': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'tenure': 'tenure'
        }
        self._id = id
        self._name = name
        self._tenure = tenure

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeeInfoSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeeInfoSchema of this EmployeeInfoSchema.  # noqa: E501
        :rtype: EmployeeInfoSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this EmployeeInfoSchema.

        The id of the employee  # noqa: E501

        :return: The id of this EmployeeInfoSchema.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this EmployeeInfoSchema.

        The id of the employee  # noqa: E501

        :param id: The id of this EmployeeInfoSchema.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this EmployeeInfoSchema.

        The employee name  # noqa: E501

        :return: The name of this EmployeeInfoSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this EmployeeInfoSchema.

        The employee name  # noqa: E501

        :param name: The name of this EmployeeInfoSchema.
        :type name: str
        """

        self._name = name

    @property
    def tenure(self) -> int:
        """Gets the tenure of this EmployeeInfoSchema.

        The tenure of an employee in days  # noqa: E501

        :return: The tenure of this EmployeeInfoSchema.
        :rtype: int
        """
        return self._tenure

    @tenure.setter
    def tenure(self, tenure: int):
        """Sets the tenure of this EmployeeInfoSchema.

        The tenure of an employee in days  # noqa: E501

        :param tenure: The tenure of this EmployeeInfoSchema.
        :type tenure: int
        """

        self._tenure = tenure
